image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - "Build"
  - "Release"

Maven Build:
  image: maven:3-jdk-8
  stage: "Build"
  script: mvn -s .m2/settings.xml clean deploy
  artifacts:
    expire_in: 1 hour
    paths:
      - target/run-codefender.jar

Docker Build:
  stage: "Release"
  variables:
    DOCKER_IMAGE: "shibme/codefender"
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
    - docker logout
  only:
    - master
