#!/usr/bin/env bash
DOCKER_VERSION_RESPONSE=$(docker -v)
EXPECTED_RESPONSE="Docker version "
if test "${DOCKER_VERSION_RESPONSE#*$EXPECTED_RESPONSE}" != "$DOCKER_VERSION_RESPONSE"; then

  if [ -z "$CODEINSPECT_GIT_SSHKEY" ]; then
    export CODEINSPECT_GIT_SSHKEY="$HOME/.ssh/id_rsa"
  fi
  if [ -z "$CODEINSPECT_CONTAINER" ]; then
    export CODEINSPECT_CONTAINER="CodeInspect-$RANDOM"
  fi
  export CODEINSPECT_CONTAINER=${CODEINSPECT_CONTAINER// /_}
  if [ -z "$CODEINSPECT_IMAGE" ]; then
    export CODEINSPECT_IMAGE="shibme/codeinspect"
    docker pull "$CODEINSPECT_IMAGE"
  fi

  CODEINSPECT_COMMAND="docker run --rm "
  CODEINSPECT_COMMAND="$CODEINSPECT_COMMAND --env-file <(env | grep CODEINSPECT_)"
  CODEINSPECT_COMMAND="$CODEINSPECT_COMMAND --env-file <(env | grep STEWARD_)"
  CODEINSPECT_COMMAND="$CODEINSPECT_COMMAND --name $CODEINSPECT_CONTAINER"
  if [ -f "$CODEINSPECT_GIT_SSHKEY" ]; then
    echo "Using SSH Key: $CODEINSPECT_GIT_SSHKEY"
    CODEINSPECT_COMMAND="$CODEINSPECT_COMMAND -v $CODEINSPECT_GIT_SSHKEY:/root/.ssh/id_rsa"
  fi
  CODEINSPECT_COMMAND="$CODEINSPECT_COMMAND -v $(pwd):/codeinspect $CODEINSPECT_IMAGE"

  echo "Starting container: $CODEINSPECT_CONTAINER"
  echo "$CODEINSPECT_COMMAND" | bash
else
  echo "Please install docker client before you begin."
  exit 1
fi
